const Unit = [
  "Ben M'sik Sidi Othmane",
  "Ahyaa Torat",
  "Arrdiyat Naciria",
  "Al Haramayn Charifayn",
  "Zaouïa Naciria",
  "Essaouira",
  "Alimara Almochtaraka",
  "El Fida et Derb Sultan",
  "Le Maristane",
  "Mohammedia et Sidi El Bernoussi",
  "Le Complexe Commercial Habous",
  "Anfa",
  "Taroudant Idriss El Harizi",
  "Tétouan",
  "Immeuble 16 Novembre",
  "Immeuble Tanger",
  "Immeuble Kaddour El Harizi",
  "Immeuble Lalla Nezha",
  "Immeuble Marhaba 6 Octobre",
  "Ain Sbaa et Hay Mohammedi",
  "Ain Chock et Hay Hassani",
  "Mosquée Hassan 2",
  "Papeterie Feddala",
  "Wassiyat Habous Bennani",
];

const Conservation = [
  "Benslimane",
  "Berrchid",
  "Casa Anfa",
  "Casa Ain Chock",
  "Casa Ain Sbaa",
  "Casa Al Fida",
  "Casa Al Maarif",
  "Casa Sidi El Bernoussi  Sidi Moumen",
  "Casa Hay Hassani",
  "Casa Nouaceur",
  "Casa Ben M'sik Sidi Othmane",
  "Mohammedia",
  "Settat",
  "Casa Mediouna",
];

const Owner = [
  "Domaine privé de l'état",
  "Habous",
  "Domaine public",
  "Domaine forestier",
  "Collectivité Territoriale",
  "Collectivité Ethnique",
  "Entité Etatique",
];

const Consistance = [
  "Maison",
  "Appartement ",
  "Local commercial",
  "Terrain nu",
  "Hôtel",
  "Hammam",
  "Four",
  "Mosquée",
  "Cimitière",
  "Parking",
  "Usufruit",
  "Immeuble",
  "Chambre",
  "Box",
];

const Assignment = [
  "Usage d'Habitat",
  "Usage de Bureau",
  "Usage Commercial",
  "Usage Industriel",
  "Usage Administratif",
  "Dépôt",
  "Crèche",
  "Hammam",
  "Four",
  "Ecole Coranique",
  "Librairie",
  "Cinéma",
  "Ecole",
  "Equipement public, voiries et espaces verts",
  "Zone d'Habitat",
  "Zone Industrielle",
  "Zone Agricole",
  "Zone Touristique",
  "Zone Logistique et Commerciale",
  "Parking",
  "Construction légère",
];

const DocumentType = ["Plan topographique", "Certificat de propriété"];

module.exports = {
  Unit,
  Conservation,
  Consistance,
  Assignment,
  DocumentType,
  Owner,
};
